name: Deploy frontend 

concurrency:
  group: frontend-deployment
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force deployment"
        required: false
        default: false
        type: boolean
      frontend-prod-enabled:
        description: "Deploy frontend prod"
        required: true
        default: true
        type: boolean
      frontend-staging-enabled:
        description: "Deploy frontend staging"
        required: true
        default: true
        type: boolean
  push:
    branches:
      - main

jobs:
  check-changes:
    uses: ./.github/workflows/check-changes.yml
    with:
      package: '@l2beat/frontend'
      force: ${{ github.event.inputs.force == 'true' }}

  build:
    needs: check-changes
    if: needs.check-changes.outputs.should_deploy == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      project: frontend
      dockerfile: packages/frontend/Dockerfile
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  deploy-frontend-prod:
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.frontend-prod-enabled != false || github.event_name != 'workflow_dispatch' && vars.DEPLOY_FRONTEND_PROD_ENABLED != 'false'
    uses: ./.github/workflows/deploy-to-coolify.yml
    secrets:
      COOLIFY_SERVER: ${{ secrets.COOLIFY_SERVER }}
      COOLIFY_DEPLOY_API_KEY: ${{ secrets.COOLIFY_DEPLOY_API_KEY }}
      COOLIFY_UUID: ${{ secrets.COOLIFY_FRONTEND_PROD_ID }}

  deploy-frontend-staging:
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.frontend-staging-enabled != false || github.event_name != 'workflow_dispatch' && vars.DEPLOY_FRONTEND_STAGING_ENABLED != 'false'
    uses: ./.github/workflows/deploy-to-coolify.yml
    secrets:
      COOLIFY_SERVER: ${{ secrets.COOLIFY_SERVER }}
      COOLIFY_DEPLOY_API_KEY: ${{ secrets.COOLIFY_DEPLOY_API_KEY }}
      COOLIFY_UUID: ${{ secrets.COOLIFY_FRONTEND_STAGING_ID }}
