name: Deploy token-backend

concurrency:
  group: token-backend-deployment
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force deployment"
        required: true
        default: true
        type: boolean
  push:
    branches:
      - main

jobs:
  check-changes:
    uses: ./.github/workflows/check-changes.yml
    with:
      package: '@l2beat/token-backend'
      force: ${{ github.event.inputs.force == 'true' }}

  build:
    needs: check-changes
    if: needs.check-changes.outputs.should_deploy == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      project: token-backend
      dockerfile: packages/token-backend/Dockerfile
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-to-coolify.yml
    secrets:
      COOLIFY_SERVER: ${{ secrets.COOLIFY_SERVER }}
      COOLIFY_DEPLOY_API_KEY: ${{ secrets.COOLIFY_DEPLOY_API_KEY }}
      COOLIFY_UUID: ${{ secrets.COOLIFY_TOKEN_BACKEND_ID }}
