name: Deploy update monitor

concurrency:
  group: update-monitor-deployment
permissions: {}

on:
  workflow_dispatch: {}
  schedule:
    - cron: "45 * * * *"

jobs:
  deploy-update-monitor:
    name: Deploy update monitor
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login to heroku container registry
        uses: docker/login-action@v3
        with:
          username: "_"
          password: ${{ secrets.HEROKU_TOKEN }}
          registry: registry.heroku.com
      - name: Build and publish containers
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.backend
          build-args: |
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          tags: |
            registry.heroku.com/${{ secrets.HEROKU_UPDATE_MONITOR_DEV }}/web
            registry.heroku.com/${{ secrets.HEROKU_UPDATE_MONITOR_PROD }}/web
      - name: Release published containers
        run: |
          heroku container:release -a ${{ secrets.HEROKU_UPDATE_MONITOR_DEV }} -v web
          heroku container:release -a ${{ secrets.HEROKU_UPDATE_MONITOR_PROD }} -v web
        env:
          HEROKU_ORGANIZATION: ${{ vars.HEROKU_ORG }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
