name: Smoke Test (PR)

on:
  pull_request:

# This job is marked as required but GitHub does not allow us to specify
# runner context (Pull Request vs. Merge Group) for which requirement applies
# thus we introduce a dummy step that will always skip the run in the PR context,
# letting us preserve the required status for the job in the Merge Group context
jobs:
  config-smoke-test:
    name: Config smoke test
    # Saves us from wasting time required to spin up the runner
    if: 1 == 0
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # It will not run but is required
      - name: Skip run in PR context
        run: echo "‚è© - Run skipped, this job is only meant to run in the Merge Group context"
